//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_MT2000_ScanItem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CS_MT2000_ScanItem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string StrAbout {
            get {
                return ResourceManager.GetString("StrAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string StrBarcode {
            get {
                return ResourceManager.GetString("StrBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string StrCancel {
            get {
                return ResourceManager.GetString("StrCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Delay.
        /// </summary>
        internal static string StrClearDelay {
            get {
                return ResourceManager.GetString("StrClearDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string StrClose {
            get {
                return ResourceManager.GetString("StrClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code128.
        /// </summary>
        internal static string StrCode128 {
            get {
                return ResourceManager.GetString("StrCode128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code39.
        /// </summary>
        internal static string StrCode39 {
            get {
                return ResourceManager.GetString("StrCode39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma.
        /// </summary>
        internal static string StrComma {
            get {
                return ResourceManager.GetString("StrComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        internal static string StrDelay {
            get {
                return ResourceManager.GetString("StrDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delimiter.
        /// </summary>
        internal static string StrDelimiter {
            get {
                return ResourceManager.GetString("StrDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string StrDone {
            get {
                return ResourceManager.GetString("StrDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quantity must be a number between 1 and {0}..
        /// </summary>
        internal static string StrErrorBadQuantity {
            get {
                return ResourceManager.GetString("StrErrorBadQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner Services couldn&apos;t be initialized..
        /// </summary>
        internal static string StrErrorCantSetScannerServicesMode {
            get {
                return ResourceManager.GetString("StrErrorCantSetScannerServicesMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner Services couldn&apos;t be started..
        /// </summary>
        internal static string StrErrorCantStartScannerServices {
            get {
                return ResourceManager.GetString("StrErrorCantStartScannerServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t send the barcode data to the host..
        /// </summary>
        internal static string StrErrorCouldntSendBarcode {
            get {
                return ResourceManager.GetString("StrErrorCouldntSendBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner Services is not running..
        /// </summary>
        internal static string StrErrorScannerServicesNotRunning {
            get {
                return ResourceManager.GetString("StrErrorScannerServicesNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string StrItem {
            get {
                return ResourceManager.GetString("StrItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string StrMenu {
            get {
                return ResourceManager.GetString("StrMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliseconds.
        /// </summary>
        internal static string StrMilliseconds {
            get {
                return ResourceManager.GetString("StrMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ms.
        /// </summary>
        internal static string StrMS {
            get {
                return ResourceManager.GetString("StrMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate.
        /// </summary>
        internal static string StrNBarcodes {
            get {
                return ResourceManager.GetString("StrNBarcodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string StrOptions {
            get {
                return ResourceManager.GetString("StrOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string StrQuantity {
            get {
                return ResourceManager.GetString("StrQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Together.
        /// </summary>
        internal static string StrQuantityDelimiterBarcode {
            get {
                return ResourceManager.GetString("StrQuantityDelimiterBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  s.
        /// </summary>
        internal static string StrS {
            get {
                return ResourceManager.GetString("StrS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Item.
        /// </summary>
        internal static string StrScanItem {
            get {
                return ResourceManager.GetString("StrScanItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string StrSeconds {
            get {
                return ResourceManager.GetString("StrSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi-colon.
        /// </summary>
        internal static string StrSemicolon {
            get {
                return ResourceManager.GetString("StrSemicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        internal static string StrTab {
            get {
                return ResourceManager.GetString("StrTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmit.
        /// </summary>
        internal static string StrTransmit {
            get {
                return ResourceManager.GetString("StrTransmit", resourceCulture);
            }
        }
    }
}
