//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_WANSample {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CS_WANSample.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting....
        /// </summary>
        internal static string attempting {
            get {
                return ResourceManager.GetString("attempting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &quot;Answer&quot; to respond..
        /// </summary>
        internal static string clickAnswerToRepsond {
            get {
                return ResourceManager.GetString("clickAnswerToRepsond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected!.
        /// </summary>
        internal static string connected {
            get {
                return ResourceManager.GetString("connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialing....
        /// </summary>
        internal static string dialing {
            get {
                return ResourceManager.GetString("dialing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected!.
        /// </summary>
        internal static string disconnected {
            get {
                return ResourceManager.GetString("disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect Failed: .
        /// </summary>
        internal static string disconnectFailed {
            get {
                return ResourceManager.GetString("disconnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed: .
        /// </summary>
        internal static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALERT: Failed to set the radio state!.
        /// </summary>
        internal static string failedToSetRadio {
            get {
                return ResourceManager.GetString("failedToSetRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   From: .
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming phone call!.
        /// </summary>
        internal static string incomingPhoneCall {
            get {
                return ResourceManager.GetString("incomingPhoneCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Sent!.
        /// </summary>
        internal static string messageSent {
            get {
                return ResourceManager.GetString("messageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Msg: .
        /// </summary>
        internal static string msg {
            get {
                return ResourceManager.GetString("msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait...\r\nRadio is being set..
        /// </summary>
        internal static string pleaseWaitRadioSet {
            get {
                return ResourceManager.GetString("pleaseWaitRadioSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio must be enabled to use this feature!.
        /// </summary>
        internal static string radioMustBeEnabled {
            get {
                return ResourceManager.GetString("radioMustBeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To physically drop the connection in this method, you will have to close all applications that are using the internet.\r\nThe connection will be dropped after a timeout.
        /// </summary>
        internal static string toPhysicallyDrop {
            get {
                return ResourceManager.GetString("toPhysicallyDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have message!.
        /// </summary>
        internal static string youHaveMessage {
            get {
                return ResourceManager.GetString("youHaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have SMS message!.
        /// </summary>
        internal static string youHaveSMSMessage {
            get {
                return ResourceManager.GetString("youHaveSMSMessage", resourceCulture);
            }
        }
    }
}
